security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_database:
            entity:
                class: App\Entity\User
                property: username
        in_memory: { memory: null }

    encoders:
        App\Entity\User:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/compo-admin
            anonymous: true

            provider: in_database

            form_login:
                login_path: admin_connexion
                check_path: admin_connexion
                default_target_path: dashboard
                always_use_default_target_path: true
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: admin_deconnexion
                target: admin_connexion
        user:
            pattern: ^/user/account
            anonymous: true

            provider: in_database

            form_login:
                login_path: user_connexion
                check_path: user_connexion
                default_target_path: member_space
                always_use_default_target_path: true
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: user_deconnexion
                target: user_connexion
        main:
            anonymous: lazy

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
    role_hierarchy:
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_USER: ROLE_USER
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/user/account/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/account/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/account, roles: ROLE_USER }

        - { path: ^/compo-admin/account/admin-connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/compo-admin/account/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/compo-admin, roles: ROLE_ADMIN }
        - { path: ^/compo-admin/administration, roles: ROLE_ADMIN }
